version: '3'

services:
  app:
    build: .
    volumes:
      - .:/samvera/hyrax-webapp
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=commarch
      - POSTGRES_USER=commarch
      - POSTGRES_PASSWORD=commarch
      - DEV_REDIS_HOST=redis
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - db
      - solr
      - fcrepo
    ports:
      - "3000:3000"

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=commarch
      - POSTGRES_USER=commarch
      - POSTGRES_PASSWORD=commarch

  redis:
    image: redis:alpine

  solr:
    image: solr:6.5.1
    volumes:
      - ./solr/conf:/opt/solr/conf
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - hydra-development
      - /opt/solr/conf
    ports:
      - "8983:8983"

  fcrepo:
    image: ualbertalib/docker-fcrepo4:4.7
    environment:
      - JAVA_OPTS=${JAVA_OPTS} -Dfcrepo.modeshape.configuration="classpath:/config/file-simple/repository.json" -Dfcrepo.object.directory="/data/objects" -Dfcrepo.binary.directory="/data/binaries"
    ports:
      - "8080:8080"

