terms:
 - id: Activity/Lab
   term: Activity/Lab
 - id: Assessment
   term: Assessment
 - id: Case Study
   term: Case Study
 - id: Data Set
   term: Data Set
 - id: Diagram/Illustration
   term: Diagram/Illustration
 - id: Full Course
   term: Full Course
 - id: Game
   term: Game
 - id: Homework/Assignment
   term: Homework/Assignment
 - id: Interactive
   term: Interactive
 - id: Lecture
   term: Lecture
 - id: Lecture Notes
   term: Lecture Notes
 - id: Lesson
   term: Lesson
 - id: Lesson Plan
   term: Lesson Plan
 - id: Module
   term: Module
 - id: Primary Source
   term: Primary Source
 - id: Reading
   term: Reading
 - id: Simulation
   term: Simulation
 - id: Student Guide
   term: Student Guide
 - id: Syllabus
   term: Syllabus
 - id: Teaching/Learning Strategy
   term: Teaching/Learning Strategy
 - id: Textbook
   term: Textbook
 - id: Unit of Study
   term: Unit of Study







