terms:
  - id: Article
    term: Article
  - id: Audio
    term: Audio
  - id: Book
    term: Book
  - id: Brochure
    term: Brochure
  - id: Conference proceeding
    term: Conference proceeding
  - id: College document
    term: College document
  - id: Dataset
    term: Dataset
  - id: Image
    term: Image
  - id: Learning object
    term: Learning object
  - id: Map
    term: Map
  - id: Newspaper
    term: Newspaper
  - id: Part of book
    term: Part of book
  - id: Poster
    term: Poster
  - id: Presentation
    term: Presentation
  - id: Project
    term: Project
  - id: Report
    term: Report
  - id: Research paper
    term: Research paper
  - id: Software
    term: Software
  - id: Video
    term: Video
  - id: Other
    term: Other
