default: &default
  setup: tinymce_nav_safety # onChange event init
content_block:
  <<: *default
  menubar: false
  toolbar1: styleselect | bold italic | undo redo
  toolbar2: bullist numlist | link | table | fullscreen | image | code
  plugins:
    - autolink
    - code
    - link
    - table
    - fullscreen
    - image
custom:
  <<: *default
