name: Containers

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Diagnostics
        run: |
          pwd
          ls -al
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push app
        id: app_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/lbcclib/community_archive/app:${{ github.sha }}
          file: .docker/Dockerfile.app
      -
        name: Build and push worker
        id: worker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/lbcclib/community_archive/worker:${{ github.sha }}
          file: .docker/Dockerfile.worker
