name: deploy

on:
  workflow_run:
    workflows: ["Containers"]
    types:
      - completed

jobs:
  deploy-staging:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITH: deployment_script
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - uses: azure/setup-kubectl@v1
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Log in to AKS
      run: az aks get-credentials --name ${{ secrets.K8S_CLUSTER_NAME }} --resource-group ${{ secrets.K8S_CLUSTER_RG }}
    - uses: azure/setup-helm@v1
      with:
        version: v3.6.3
    - name: Run deploy script
      run: bundle exec ruby .helm/deploy.rb upgrade ${{ github.sha }}
